CREATE DATABASE IF NOT EXISTS taskteam CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE taskteam;

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
